import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { createClient, type SupabaseClient } from '@supabase/supabase-js'

type Vote = { id:string; name:string; team:'boy'|'girl'; weight:number; day:number; babyName:string }
type Wish = { id:string; name:string; message:string }
type Entry = { id:string; name:string; score:number }
// These are public browser credentials. Keep privileged service-role keys out of this file.
const url = (import.meta.env.VITE_SUPABASE_URL as string | undefined) || 'https://jlaksmssscjhbntwenjv.supabase.co'
const key = (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) || 'sb_publishable_Br0Eg5rSx-HigV2glMl1eQ_SbHvD-zj'
const db = createClient(url, key)
const questions = [
 ['چه کسی احتمالاً زودتر با گریهٔ کوچولو بیدار می‌شود؟',0],
 ['چه کسی بیشتر برای کوچولو خرید می‌کند؟',1],
 ['چه کسی موقع لالایی خواندن زودتر خوابش می‌برد؟',1],
 ['چه کسی بیشتر از کوچولو عکس می‌گیرد؟',0],
 ['چه کسی قوانین خواب را زودتر زیر پا می‌گذارد؟',1],
 ['چه کسی نگران کوچک‌ترین عطسه می‌شود؟',0],
 ['چه کسی اسباب‌بازی را قبل از تولد باز می‌کند؟',1],
 ['چه کسی در انتخاب لباس‌ها دست‌ودلبازتر است؟',0],
 ['چه کسی قصه‌های بامزه‌تری تعریف می‌کند؟',1],
 ['چه کسی می‌گوید «فقط پنج دقیقهٔ دیگه بغلش کنم»؟',0],
] as const
const demo:Vote[] = [
 {id:'demo1',name:'مهمان نمونه',team:'girl',weight:3.2,day:18,babyName:'آوا'},
 {id:'demo2',name:'دوست خانواده',team:'boy',weight:3.5,day:20,babyName:'آراد'},
 {id:'demo3',name:'یکی از فامیل‌ها',team:'girl',weight:3.1,day:18,babyName:'رها'},
]
function stored<T>(key:string, fallback:T):T { try { const v=localStorage.getItem('ssbabay-'+key); return v ? JSON.parse(v) as T : fallback } catch { return fallback } }
export default function App() {
 const [tab,setTab]=useState<'vote'|'quiz'|'wishes'|'screen'|'admin'>('vote')
 const [votes,setVotes]=useState<Vote[]>(()=>stored('votes',demo))
 const [wishes,setWishes]=useState<Wish[]>(()=>stored('wishes',[]))
 const [entries,setEntries]=useState<Entry[]>(()=>stored('entries',[]))
 const [name,setName]=useState(''),[team,setTeam]=useState<'boy'|'girl'|''>(''),[weight,setWeight]=useState('3.3'),[day,setDay]=useState('18'),[babyName,setBabyName]=useState('')
 const [wishName,setWishName]=useState(''),[message,setMessage]=useState('')
 const [quizName,setQuizName]=useState(''),[answers,setAnswers]=useState<number[]>([]),[done,setDone]=useState(false),[notice,setNotice]=useState('')
 useEffect(()=>{localStorage.setItem('ssbabay-votes',JSON.stringify(votes));localStorage.setItem('ssbabay-wishes',JSON.stringify(wishes));localStorage.setItem('ssbabay-entries',JSON.stringify(entries))},[votes,wishes,entries])
 useEffect(()=>{if(!db)return;const ch=db.channel('ssbabay-live').on('postgres_changes',{event:'*',schema:'public',table:'votes'},()=>void refreshVotes()).on('postgres_changes',{event:'*',schema:'public',table:'wishes'},()=>void refreshWishes()).on('postgres_changes',{event:'*',schema:'public',table:'quiz_entries'},()=>void refreshEntries()).subscribe();void refreshVotes();void refreshWishes();void refreshEntries();return()=>{void db.removeChannel(ch)}},[])
 async function refreshVotes(){if(!db)return;const {data}=await db.from('votes').select('*').order('created_at',{ascending:false});if(data)setVotes(data.map((v:any)=>({id:v.id,name:v.name,team:v.team,weight:Number(v.weight),day:Number(v.day),babyName:v.baby_name||''})))}
 async function refreshWishes(){if(!db)return;const {data}=await db.from('wishes').select('*').order('created_at',{ascending:false});if(data)setWishes(data.map((v:any)=>({id:v.id,name:v.name,message:v.message})))}
 async function refreshEntries(){if(!db)return;const {data}=await db.from('quiz_entries').select('*').order('score',{ascending:false});if(data)setEntries(data.map((v:any)=>({id:v.id,name:v.name,score:v.score})))}
 async function vote(e:FormEvent){e.preventDefault();if(!team||!name.trim()){setNotice('نامت را وارد کن و یکی از تیم‌ها را انتخاب کن 💗');return}const item={id:crypto.randomUUID(),name:name.trim(),team,weight:Number(weight),day:Number(day),babyName:babyName.trim()};if(db){const {error}=await db.from('votes').insert({name:item.name,team:item.team,weight:item.weight,day:item.day,baby_name:item.babyName});if(error){setNotice('ثبت رأی ناموفق بود؛ تنظیمات Supabase را بررسی کنید.');return}await refreshVotes()}else setVotes(old=>[item,...old]);setName('');setBabyName('');setNotice('رأی تو ثبت شد! ممنون که در جشن ما هستی 🎉')}
 async function wish(e:FormEvent){e.preventDefault();if(!wishName.trim()||!message.trim())return;const item={id:crypto.randomUUID(),name:wishName.trim(),message:message.trim()};if(db){const {error}=await db.from('wishes').insert(item);if(error){setNotice('ثبت پیام ناموفق بود.');return}await refreshWishes()}else setWishes(old=>[item,...old]);setWishName('');setMessage('');setNotice('آرزوی تو ثبت شد 💌')}
 async function quiz(e:FormEvent){e.preventDefault();if(!quizName.trim()||answers.length!==questions.length){setNotice('نامت را بنویس و به همهٔ سؤال‌ها جواب بده.');return}const score=answers.reduce((s,a,i)=>s+(a===questions[i][1]?1:0),0);const item={id:crypto.randomUUID(),name:quizName.trim(),score};if(db){const {error}=await db.from('quiz_entries').insert(item);if(error){setNotice('ثبت امتیاز ناموفق بود.');return}await refreshEntries()}else setEntries(old=>[...old,item].sort((a,b)=>b.score-a.score));setDone(true);setNotice('امتیازت ثبت شد! 🌟')}
 const boy=votes.filter(v=>v.team==='boy').length,girl=votes.length-boy,pct=votes.length?Math.round(boy/votes.length*100):0
 const avg=useMemo(()=>votes.length?votes.reduce((s,v)=>s+v.weight,0)/votes.length:0,[votes])
 const days=useMemo(()=>Object.entries(votes.reduce((a,v)=>({...a,[v.day]:(a[v.day]||0)+1}),{} as Record<number,number>)).sort((a,b)=>b[1]-a[1]),[votes])
 function exportWishes(){const html='<!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><title>دفتر یادگاری سارا و سعید</title><style>body{font-family:Tahoma,sans-serif;max-width:800px;margin:40px auto;color:#554253;line-height:2}h1{text-align:center;color:#c36f98}.note{border:1px solid #efd8e5;border-radius:12px;padding:18px;margin:14px 0;break-inside:avoid}</style><h1>دفتر یادگاری کوچولوی سارا و سعید ♡</h1>'+wishes.map(w=>'<div class="note"><p>'+escapeHtml(w.message).replace(/\n/g,'<br>')+'</p><b>با عشق، '+escapeHtml(w.name)+'</b></div>').join('')+'</html>';const blob=new Blob([html],{type:'text/html;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sara-saeed-wishes.html';a.click();URL.revokeObjectURL(a.href);setNotice('دفتر یادگاری دانلود شد؛ فایل را در مرورگر باز کن و برای ذخیرهٔ PDF گزینهٔ چاپ را بزن.')}
 function escapeHtml(s:string){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}
 const screen=tab==='screen'
 return <div className={'app '+(screen?'tv-mode':'')}>
 <header className="hero"><div className="hero-top"><span className="pill">یک عشق کوچولو در راه است</span><span className="heart">♡</span></div><div className="hero-art"><span className="cloud cloud-a">☁</span><span className="moon">☾</span><span className="cloud cloud-b">☁</span><span className="star star-a">✦</span><span className="baby">♡</span></div><p className="eyebrow">BABY SHOWER CELEBRATION</p><h1>جشن کوچولوی <span>سارا و سعید</span></h1><p className="hero-sub">با عشق کنار هم جمع شدیم تا آمدن قشنگ‌ترین اتفاق زندگی را جشن بگیریم.</p>{!screen&&<div className="hero-tags"><span>💙 تیم پسر</span><span>💖 تیم دختر</span><span>🎁 کلی خاطرهٔ شیرین</span></div>}</header>
 {!screen&&<nav className="tabs"><button className={tab==='vote'?'active':''} onClick={()=>setTab('vote')}>🗳️ رأی‌گیری</button><button className={tab==='quiz'?'active':''} onClick={()=>setTab('quiz')}>👨‍👩‍👧 مامان یا بابا؟</button><button className={tab==='wishes'?'active':''} onClick={()=>setTab('wishes')}>💌 دفتر یادگاری</button><button onClick={()=>setTab('screen')}>📺 نمایشگر جشن</button><button className={tab==='admin'?'active':''} onClick={()=>setTab('admin')}>🔐 مدیریت</button></nav>}
 {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 {tab==='vote'&&<main className="content two-col"><section className="card"><Heading icon="🎀" title="حدس بزن کوچولو کیه!" sub="رأی تو رو می‌شماریم؛ آماده‌ای؟"/><form className="form" onSubmit={vote}><label>اسمت چیه؟<input value={name} onChange={e=>setName(e.target.value)} placeholder="اسم قشنگت رو بنویس" required maxLength={60}/></label><div className="label-title">به کدوم تیم رأی می‌دی؟</div><div className="team-options"><button type="button" className={'team team-boy '+(team==='boy'?'chosen':'')} onClick={()=>setTeam('boy')}><span className="team-emoji">🧸</span><strong>تیم پسر</strong><span>آبی و دوست‌داشتنی</span></button><button type="button" className={'team team-girl '+(team==='girl'?'chosen':'')} onClick={()=>setTeam('girl')}><span className="team-emoji">🎀</span><strong>تیم دختر</strong><span>صورتی و شیرین</span></button></div><div className="field-row"><label>وزن کوچولو (کیلوگرم)<select value={weight} onChange={e=>setWeight(e.target.value)}>{Array.from({length:21},(_,i)=>(2.5+i*.1).toFixed(1)).map(v=><option key={v}>{v}</option>)}</select></label><label>حدس روز تولد<select value={day} onChange={e=>setDay(e.target.value)}>{Array.from({length:31},(_,i)=>String(i+1)).map(v=><option key={v}>{v}</option>)}</select></label></div><label>اسم پیشنهادی تو (اختیاری)<input value={babyName} onChange={e=>setBabyName(e.target.value)} placeholder="مثلاً آوا، آراد، رها..." maxLength={50}/></label><button className="primary-btn">ثبت رأی من ♡</button></form></section><section className="card results-card"><Heading icon="📊" title="نبض جشن" sub="نتیجهٔ رأی‌های ثبت‌شده"/><div className="vote-total"><strong>{votes.length}</strong><span>رأی ثبت‌شده</span></div><div className="vote-bar"><div className="bar-boy" style={{width:pct+'%'}}/><div className="bar-girl" style={{width:(100-pct)+'%'}}/></div><div className="percentages"><div><span className="dot blue"/>تیم پسر <strong>{pct}٪</strong><small>{boy} رأی</small></div><div><span className="dot pink"/>تیم دختر <strong>{100-pct}٪</strong><small>{girl} رأی</small></div></div><div className="mini-stats"><div><span>⚖️</span><small>میانگین وزن حدسی</small><strong>{avg.toFixed(2)} کیلو</strong></div><div><span>📅</span><small>روز محبوب تولد</small><strong>{days[0]?'روز '+days[0][0]:'هنوز ثبت نشده'}</strong></div></div><div className="name-cloud"><h3>✨ اسم‌های پیشنهادی</h3><div>{votes.filter(v=>v.babyName).slice(0,18).map(v=><span key={v.id}>{v.babyName}</span>)}</div></div></section></main>}
 {tab==='quiz'&&<main className="content quiz-layout"><section className="card"><Heading icon="💘" title="مامان یا بابا؟" sub="ببین چقدر سارا و سعید رو می‌شناسی!"/>{!done?<form className="form" onSubmit={quiz}><label>اسم شرکت‌کننده<input value={quizName} onChange={e=>setQuizName(e.target.value)} placeholder="نامت رو وارد کن" required/></label>{questions.map(([q],i)=><div className="question" key={q}><strong><span>{String(i+1).padStart(2,'0')}</span>{q}</strong><div className="answer-options">{['سارا مامان','سعید بابا'].map((a,j)=><button type="button" key={a} className={answers[i]===j?'selected':''} onClick={()=>setAnswers(old=>{const next=[...old];next[i]=j;return next})}>{a}</button>)}</div></div>)}<button className="primary-btn">ثبت جواب‌ها و دیدن امتیاز ✨</button></form>:<div className="quiz-success"><div>🏆</div><h3>جواب‌هات ثبت شد!</h3><p>نتیجه در جدول امتیازها قرار گرفت.</p><button className="secondary-btn" onClick={()=>{setDone(false);setAnswers([]);setQuizName('')}}>شرکت دوباره</button></div>}</section><aside className="card"><Heading icon="🏆" title="قهرمان‌های شناخت" sub="بیشترین جواب درست"/>{[...entries].sort((a,b)=>b.score-a.score).slice(0,10).map((v,i)=><div className="rank-row" key={v.id}><span className="rank">{['🥇','🥈','🥉'][i]||i+1}</span><span>{v.name}</span><strong>{v.score}/10</strong></div>)}{!entries.length&&<p className="empty">هنوز کسی شرکت نکرده؛ اولین نفر باش!</p>}</aside></main>}
 {tab==='wishes'&&<main className="content two-col"><section className="card"><Heading icon="💌" title="برای کوچولو بنویس..." sub="یک آرزوی قشنگ برای شروع زندگی‌اش"/><form className="form" onSubmit={wish}><label>اسم تو<input value={wishName} onChange={e=>setWishName(e.target.value)} required maxLength={60} placeholder="با عشق، از طرف..."/></label><label>پیام و آرزوی تو<textarea value={message} onChange={e=>setMessage(e.target.value)} required maxLength={1200} rows={5} placeholder="عزیز کوچولو، برات آرزو می‌کنم..."/></label><button className="primary-btn">ثبت آرزو 💗</button></form></section><section className="card"><Heading icon="📖" title="دفتر خاطرات کوچولو" sub={wishes.length+' پیام پر از عشق'}/><div className="wishes-list">{wishes.map(w=><article className="wish-note" key={w.id}><p>{w.message}</p><strong>با عشق، {w.name}</strong></article>)}</div>{!wishes.length&&<p className="empty">اولین آرزو را بنویس 💕</p>}<button className="secondary-btn export-btn" onClick={exportWishes} disabled={!wishes.length}>دانلود دفتر یادگاری (قابل چاپ به PDF)</button></section></main>}
 {tab==='admin'&&<AdminPanel db={db}/>}
 {tab==='screen'&&<main className="content screen-layout"><div className="screen-title"><span>✨ جشن کوچولوی سارا و سعید ✨</span><h2>حدس مهمان‌ها چیه؟</h2><p>هر رأی، یک تکه از هیجان این روز قشنگه!</p></div><section className="screen-votes"><div className="screen-team blue-panel"><span>🧸</span><h3>تیم پسر</h3><strong>{pct}٪</strong><p>{boy} رأی</p></div><div className="screen-center"><span>♡</span><strong>{votes.length}</strong><small>رأی تا این لحظه</small><div className="vote-bar"><div className="bar-boy" style={{width:pct+'%'}}/><div className="bar-girl" style={{width:(100-pct)+'%'}}/></div></div><div className="screen-team pink-panel"><span>🎀</span><h3>تیم دختر</h3><strong>{100-pct}٪</strong><p>{girl} رأی</p></div></section><section className="screen-bottom"><div className="card"><h3>⚖️ میانگین وزن حدسی</h3><strong>{avg.toFixed(2)} کیلوگرم</strong></div><div className="card"><h3>💌 آرزوهای تازه</h3><p>{wishes.slice(0,2).map(w=>'«'+w.message+'» — '+w.name).join('　 ✧　 ')||'پیام‌های دوست‌داشتنی مهمان‌ها به‌زودی اینجا نمایش داده می‌شوند.'}</p></div></section><button className="secondary-btn back-btn" onClick={()=>setTab('vote')}>بازگشت به رأی‌گیری</button></main>}
 <footer className="footer"><span>ساخته‌شده با عشق برای سارا و سعید</span><span>♡ کوچولوی دوست‌داشتنی ♡</span>{!db&&<small>حالت پیش‌نمایش: داده‌ها فقط در همین مرورگر ذخیره می‌شوند؛ برای رأی‌گیری مشترک Supabase را تنظیم کنید.</small>}</footer></div>
}
function Heading({icon,title,sub}:{icon:string;title:string;sub:string}){return <div className="section-heading"><span className="icon">{icon}</span><div><h2>{title}</h2><p>{sub}</p></div></div>}

function AdminPanel({db}:{db:SupabaseClient}) {
 const [username,setUsername]=useState('admin'),[password,setPassword]=useState('')
 const [userId,setUserId]=useState<string|null>(null),[checking,setChecking]=useState(true)
 const [adminError,setAdminError]=useState(''),[adminNote,setAdminNote]=useState('')
 const [adminVotes,setAdminVotes]=useState<any[]>([]),[adminWishes,setAdminWishes]=useState<any[]>([]),[adminEntries,setAdminEntries]=useState<any[]>([])
 const [section,setSection]=useState<'votes'|'wishes'|'quiz_entries'>('votes')
 useEffect(()=>{let alive=true;void (async()=>{const {data}=await db.auth.getSession();if(data.session?.user){const {data:role}=await db.from('admin_users').select('user_id').eq('user_id',data.session.user.id).maybeSingle();if(alive&&role)setUserId(data.session.user.id);else if(data.session?.user)await db.auth.signOut()}if(alive)setChecking(false)})();return()=>{alive=false}},[db])
 async function loadAdminData(){const [v,w,q]=await Promise.all([db.from('votes').select('*').order('created_at',{ascending:false}),db.from('wishes').select('*').order('created_at',{ascending:false}),db.from('quiz_entries').select('*').order('created_at',{ascending:false})]);if(v.error||w.error||q.error){setAdminError('دریافت داده‌ها ناموفق بود. SQL پنل مدیریت و مجوزها را بررسی کن.');return}setAdminVotes(v.data||[]);setAdminWishes(w.data||[]);setAdminEntries(q.data||[])}
 useEffect(()=>{if(userId)void loadAdminData()},[userId])
 async function login(e:FormEvent){e.preventDefault();setAdminError('');setAdminNote('');if(username.trim().toLowerCase()!=='admin'){setAdminError('نام کاربری باید admin باشد.');return}const {data,error}=await db.auth.signInWithPassword({email:'admin@ssbabay.local',password});if(error||!data.user){setAdminError('ورود انجام نشد. حساب مدیر را در Supabase Auth بساز و رمز را بررسی کن.');return}const {data:role,error:roleError}=await db.from('admin_users').select('user_id').eq('user_id',data.user.id).maybeSingle();if(roleError||!role){await db.auth.signOut();setAdminError('این حساب هنوز دسترسی مدیر ندارد. شناسهٔ کاربر را در جدول admin_users ثبت کن.');return}setUserId(data.user.id);setPassword('')}
 async function logout(){await db.auth.signOut();setUserId(null);setAdminVotes([]);setAdminWishes([]);setAdminEntries([])}
 async function removeRecord(table:'votes'|'wishes'|'quiz_entries',id:string){if(!window.confirm('این رکورد برای همیشه حذف شود؟'))return;const {error}=await db.from(table).delete().eq('id',id);if(error){setAdminError('حذف ناموفق بود؛ سیاست دسترسی مدیر در schema.sql را اجرا کن.');return}await loadAdminData();setAdminNote('رکورد حذف شد.')}
 if(checking)return <main className="content"><section className="card admin-card"><p>در حال بررسی نشست مدیر…</p></section></main>
 if(!userId)return <main className="content admin-layout"><section className="card admin-card"><Heading icon="🔐" title="ورود به پنل مدیریت" sub="دسترسی فقط برای حساب ثبت‌شده در فهرست مدیران"/><form className="form" onSubmit={login}><label>نام کاربری<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required/></label><label>رمز عبور<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button className="primary-btn">ورود امن به پنل</button></form>{adminError&&<p className="admin-error" role="alert">{adminError}</p>}<p className="admin-help">حساب مدیر با نام کاربری <b>admin</b> به ایمیل داخلی <code>admin@ssbabay.local</code> نگاشت می‌شود. این حساب باید یک‌بار در Supabase Auth ساخته و سپس در جدول <code>admin_users</code> مجاز شود.</p></section></main>
 return <main className="content admin-layout"><section className="card admin-card"><div className="admin-header"><div><Heading icon="🛡️" title="پنل مدیریت جشن" sub="مدیریت رأی‌ها، آرزوها و امتیازهای مسابقه"/></div><button className="secondary-btn" onClick={logout}>خروج امن</button></div><div className="admin-stats"><div><small>رأی‌ها</small><strong>{adminVotes.length}</strong></div><div><small>آرزوها</small><strong>{adminWishes.length}</strong></div><div><small>شرکت‌کنندگان مسابقه</small><strong>{adminEntries.length}</strong></div></div><div className="admin-sections"><button className={section==='votes'?'active':''} onClick={()=>setSection('votes')}>رأی‌ها</button><button className={section==='wishes'?'active':''} onClick={()=>setSection('wishes')}>آرزوها</button><button className={section==='quiz_entries'?'active':''} onClick={()=>setSection('quiz_entries')}>مسابقه</button><button onClick={()=>void loadAdminData()}>↻ تازه‌سازی</button></div>{adminError&&<p className="admin-error" role="alert">{adminError}</p>}{adminNote&&<p className="admin-note" role="status">{adminNote}</p>}
 {section==='votes'&&<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>نام</th><th>تیم</th><th>وزن</th><th>روز</th><th>اسم پیشنهادی</th><th>عملیات</th></tr></thead><tbody>{adminVotes.map(v=><tr key={v.id}><td>{v.name}</td><td>{v.team==='boy'?'پسر':'دختر'}</td><td>{v.weight}</td><td>{v.day}</td><td>{v.baby_name||'—'}</td><td><button className="delete-btn" onClick={()=>void removeRecord('votes',v.id)}>حذف</button></td></tr>)}</tbody></table>{!adminVotes.length&&<p className="empty">هنوز رأیی ثبت نشده است.</p>}</div>}
 {section==='wishes'&&<div className="admin-records">{adminWishes.map(w=><article className="admin-record" key={w.id}><div><strong>{w.name}</strong><p>{w.message}</p><small>{w.created_at?new Date(w.created_at).toLocaleString('fa-IR'):''}</small></div><button className="delete-btn" onClick={()=>void removeRecord('wishes',w.id)}>حذف</button></article>)}{!adminWishes.length&&<p className="empty">هنوز آرزویی ثبت نشده است.</p>}</div>}
 {section==='quiz_entries'&&<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>نام شرکت‌کننده</th><th>امتیاز</th><th>زمان ثبت</th><th>عملیات</th></tr></thead><tbody>{adminEntries.map(q=><tr key={q.id}><td>{q.name}</td><td>{q.score}/10</td><td>{q.created_at?new Date(q.created_at).toLocaleString('fa-IR'):'—'}</td><td><button className="delete-btn" onClick={()=>void removeRecord('quiz_entries',q.id)}>حذف</button></td></tr>)}</tbody></table>{!adminEntries.length&&<p className="empty">هنوز امتیازی ثبت نشده است.</p>}</div>}
 </section></main>
}
